import * as utils from "../utils.js";
import { setDoc, doc } from 'firebase/firestore';
import { db } from "../firebase.js";

export default class Dish {
    static COLLECTION = "menu";

    constructor(name, allergens, image, houseAvailability, meals, course, priority, customerPrice, instructions, description, photoUrl) {
        //console.log(`name: ${name}`);
        
        this.name              = name; 
        this.allergens         = allergens;
        this.image             = image;
        this.houseAvailability = houseAvailability;
        this.meals             = meals;
        this.course            = course;
        this.priority          = priority;
        this.customerPrice     = customerPrice;
        this.instructions      = instructions;
        this.description       = description;

        this.isAvailable       = true;
        this.isFavorite        = false;

        this.photoUrl          = photoUrl;

        this.id = this.id();
    }

    data() {
        return {
            "allergens"         : this.allergens,
            "instructions"      : this.instructions,
            "description"       : this.description,
            "houseAvailability" : this.houseAvailability,
            "image"             : this.image,
            "isAvailable"       : this.isAvailable,
            "isFavorite"        : this.isFavorite,
            "meals"             : this.meals,
            "course"            : this.course,
            "priority"          : this.priority,
            "name"              : this.name,
            "customerPrice"     : this.customerPrice,
            "photoUrl"          : this.photoUrl
        }
    }

    id() {
        const id = utils.isString(this.name) ? this.name.toLowerCase().replace(/ /g, "-") : "";
        const meals = this.meals.join("-");
        return `${id}-${meals}`;
    }

    async upload(onError) {
        if(utils.isEmpty(this.id)) {
            onError("ID is empty");
            return false;
        }

        const data = this.data();
        try {
            const ref = doc(db, ...[Dish.COLLECTION], this.id);
            const addResult = await setDoc(ref, data);
            return addResult;
        } catch(e) {
            onError(`Error on dish upload ${this.id}: ${e.message}`);
            return false;
        }
    } 

    static async seed() {
        // todo: might need wingko and "i love bali toast" twice. Extra breakfast items are 80k. But wingko as dessert is 60k
    
        const dishes = [         
            //        name                                          allergens         image   house availability                   meal                                               course     priority  customerPrice instructions   descriptions
            new Dish("Smoothie Bowl Of Seasonal Fruits",            ["nuts"],            "", ["harmony hill"                   ], ["breakfast"                   , "snack", "extra"], "mains",    200,             80000,  "",               "Topped with our homemade granola and fresh sliced fruits - ask us what's in season if you wish to customize"                                                          , null),
            new Dish("Javanese Wingko Waffle",                      ["coconut"],         "", ["harmony hill", "the jungle nook"], ["breakfast"                   ,          "extra"], "mains",    200,             80000,  "",               "Chewy, coconutty and crispy, baked in an authentic cast waffle iron, served with our homemade jam and fresh fruit"                                                    , "gs://harmonyhill-1.firebasestorage.app/resources/menu/wingko-waffle.png"),
            new Dish("Plant Power Breakfast",                       ["soy"],             "", ["harmony hill", "the jungle nook"], ["breakfast"                   , "snack", "extra"], "mains",    200,             80000,  "",               "Scrambled tofu, served with baked potatoes, roasted tomato, garlic, spinach and seasonal sauteed veggies"                                                             , null),
            new Dish("Nasi Goreng 2.0",                             ["soy"],             "", ["harmony hill", "the jungle nook"], ["breakfast"                   , "snack", "extra"], "mains",    200,             80000,  "",               "Indonesia's classic fried rice, boosted with brown rice, seasonal veggies, tempeh and tofu"                                                                           , "gs://harmonyhill-1.firebasestorage.app/resources/menu/nasi-goreng-2.0.png"),
            new Dish("Colorful Chia Seed Pudding, normal (santan)", ["coconut"],         "", ["harmony hill", "the jungle nook"], ["breakfast"                   , "snack", "extra"], "mains",    200,             80000,  "",               "Indonesia's classic fried rice, boosted with brown rice, seasonal veggies, tempeh and tofu"                                                                           , "gs://harmonyhill-1.firebasestorage.app/resources/menu/chia-pudding.png"),
            new Dish("Colorful Chia Seed Pudding, Oat Milk",        [""],                "", ["harmony hill", "the jungle nook"], ["breakfast"                   , "snack", "extra"], "mains",    200,             80000,  "",               "Indonesia's classic fried rice, boosted with brown rice, seasonal veggies, tempeh and tofu"                                                                           , "gs://harmonyhill-1.firebasestorage.app/resources/menu/chia-pudding.png"),
            new Dish("I Love Bali Toast",                           ["soy"],             "", ["harmony hill", "the jungle nook"], ["breakfast"                   ,          "extra"], "mains",    200,             80000,  "",               "Toasted sourdough, half topped with scrambled tofu and half topped with smashed avocado, garnished with mixed seeds and roasted tomatoes"                             , "gs://harmonyhill-1.firebasestorage.app/resources/menu/i-love-bali-toast.png"),
            new Dish("Set Menu",                                    [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,            200000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Edamame With Bali Sea Salt",                  [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             50000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Carrot Ginger Soup",                          [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             50000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Pumpkin Soup",                                [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             50000,  "",               ""                                                                                                                                                                     , "gs://harmonyhill-1.firebasestorage.app/resources/menu/pumpkin-soup.png"),
            new Dish("Vegetables And Tofu Soup",                    ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             50000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Tomato Veggies Soup",                         [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             60000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Guacarosti",                                  [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             60000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Gado-Gado Rolls",                             ["peanut"],          "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             60000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Treenut Cheeze Platter",                      ["nuts"],            "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "starters", 100,             420000, "",               ""                                                                                                                                                                     , null),  
            new Dish("Lentil Bolognese",                            ["seeds"],           "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Treat yourself to Made’s famous spaghetti bolognese, loved by all. Can also be served with rice"                                                                      , null),
            new Dish("Mexican Bowl",                                ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Eat the rainbow with our protein-packed chile sin carne, accompanied by guacamole and tomato-corn salsa. Served with brown rice"                                      , "gs://harmonyhill-1.firebasestorage.app/resources/menu/mexican-bowl.png"),
            new Dish("Sushi",                                       [],                  "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Colorful sushi rolls with our homemade watermelon “toona”, marinated tofu and raw veggies inside"                                                                     , null),
            new Dish("Tempeh Steak",                                ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Flavorfully marinated tempeh drizzled with Made's secret sauce, served with baby potatoes and Balinese \"Urab\" veggies"                                              , null),
            new Dish("Chickpea Curry",                              ["coconut"],         "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Chickpeas, potatoes, tomatoes and coconut cream blend together with a fragrant spice mix to warm your tummy served with brown rice"                                   , "gs://harmonyhill-1.firebasestorage.app/resources/menu/chickpea-curry.png"),
            new Dish("Mediterranean Eggplant Stew",                 ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Tomatoes, eggplant, chickpeas meet on a bed of mashed :) Served with crispy tempeh for an extra protein boost"                                                        , null),
            new Dish("Marry Me Pasta",                              ["cashews"],         "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Deliciously creamy cashew-based sauce packed with veggies and herbs - Prepare to fall in love!"                                                                       , "gs://harmonyhill-1.firebasestorage.app/resources/menu/marry-me-pasta.png"),
            new Dish("Healthy Bowl",                                ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Healthful bowl with teriyaki glazed tempeh, vegan \"honey\" mustard dressing and a colorful mix of raw  and steamed seasonal veggies. Served with brown rice"         , null),
            new Dish("Nasi Campur",                                 ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "The way we love to eat in Bali: Rice in the middle surrounded by 4-5 seasonal veggies and tempeh/tofu preparations"                                                   , null),
            new Dish("Poke Bowl",                                   ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Homemade watermelon \"toona\", marinated tofu, edamame, avocado, cucumber and pickled ginger, served with sushi rice and homemade ginger soy dressing"                , null),
            new Dish("Savoury Tempeh Mushroom Stew",                ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "mains",    200,             100000, "",               "Tempeh in a super creamy mushroom sauce, served with baked apple, mashed potatoes and steamed veggie of the day"                                                      , "gs://harmonyhill-1.firebasestorage.app/resources/menu/mushroom-tempeh-stew.png"),
            new Dish("I Love Bali Toast",                           ["soy"],             "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack",        ], "mains",    200,             100000, "",               "Toasted sourdough, half topped with scrambled tofu and half topped with smashed avocado, garnished with mixed seeds and roasted tomatoes"                             , "gs://harmonyhill-1.firebasestorage.app/resources/menu/i-love-bali-toast.png"),
            new Dish("Javanese Wingko Waffle",                      ["coconut"],         "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack",        ], "desserts", 300,             60000,  "",               "Traditional Balinese crepes filled with grated coconut, served with fresh fruits"                                                                                     , "gs://harmonyhill-1.firebasestorage.app/resources/menu/wingko-waffle.png"),
            new Dish("Dadar Gulung",                                ["coconut, gluten"], "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "",               "Traditional Balinese crepes filled with grated coconut, served with fresh fruits"                                                                                     , null),
            new Dish("Cookies And Cream Cake",                      ["nuts, gluten"],    "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "",               "Melt in your mouth oreo goodness"                                                                                                                                     , null),
            new Dish("Chocolate Caramel Cake",                      ["nuts"],            "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "a.k.a Marz",     "Gooey caramel goodness"                                                                                                                                               , null),
            new Dish("Mango Coconut Cheese Cake",                   ["coconut"],         "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "",               "A fruity kick in the summer heat"                                                                                                                                     , null),
            new Dish("Forest Berry Cheese Cake",                    [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "",               "Something juicy to berry your nose in"                                                                                                                                , "gs://harmonyhill-1.firebasestorage.app/resources/menu/forest-berry-cheesecake.png"),
            new Dish("Brookies (2 pcs)",                            [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "Serve 2 pieces", "Yummy mix between a brownie and a cookie"                                                                                                                             , null),
            new Dish("Biscoff Caramel Peanut Slice (Square)",       [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             50000,  "",               "Small in size, but packs a punch!"                                                                                                                                    , "gs://harmonyhill-1.firebasestorage.app/resources/menu/biscoff-slice.png"),
            new Dish("Biscoff Cheesecake (Round)",                  [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             60000,  "",               "Small in size, but packs a punch!"                                                                                                                                    , null),
            new Dish("Chocolate Chip Cookie",                       [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             35000,  "",               ""                                                                                                                                                                     , "gs://harmonyhill-1.firebasestorage.app/resources/menu/chocolate-chip-cookie.png"),
            new Dish("Peanut Butter Chocolate Cookie",              [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner", "snack", "extra"], "desserts", 300,             35000,  "",               ""                                                                                                                                                                     , "gs://harmonyhill-1.firebasestorage.app/resources/menu/peanut-butter-cookie.png"),
            new Dish("Fruit Platter",                               [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "desserts", 300,             40000,  "",               ""                                                                                                                                                                     , null),           
            new Dish("Ice Cream Sticks",                            [""],                "", ["harmony hill", "the jungle nook"], [             "lunch", "dinner"         , "extra"], "desserts", 300,             35000,  "",               "See the freezer"                                                                                                                                                      , null), 
            new Dish("Seasonal Juice",                              [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             35000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Pineapple Juice",                             [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             35000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Papaya Juice",                                [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             35000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Banana Juice",                                [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             35000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Watermelon Juice",                            [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             35000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Passionfruit Juice (Seasonal)",               [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             45000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Mango Juice (Seasonal)",                      [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             45000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Passionfruit Banana Smoothie",                [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             50000,  "",               "With passion fruit from our garden"                                                                                                                                   , null),
            new Dish("Pina Colada Smoothie",                        [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             50000,  "",               "Pineapple banana coconut goodness"                                                                                                                                    , null),
            new Dish("Strawberry Smoothie",                         [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             50000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Mango Banana Smoothie",                       [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             50000,  "",               "It's finally here! Mango season!"                                                                                                                                     , null),  
            new Dish("Bottle Of Jamu",                              [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             80000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Glass Of Jamu",                               [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             50000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Young Coconut",                               [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "drinks",   400,             40000,  "",               ""                                                                                                                                                                     , null), 
            new Dish("Probiotic Kombucha",                          [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner"         , "extra"], "drinks",   400,             0,      "",               ""                                                                                                                                                                     , null),
            new Dish("Sparkling Water",                             [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner"         , "extra"], "drinks",   400,             0,      "",               ""                                                                                                                                                                     , null),
            new Dish("Soda",                                        [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner"         , "extra"], "drinks",   400,             0,      "",               "Coke, Coke Zero, Schweppes"                                                                                                                                           , null),
            new Dish("Espresso",                                    [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             30000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Americano",                                   [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             30000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Latte with oatmilk",                          [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             40000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Cappuccino with oatmilk",                     [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             40000,  "",               ""                                                                                                                                                                     , null),
            new Dish("Sacred Cacao with oatmilk",                   [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             60000,  "",               "Intense hot chocolate with ceremonial grade cacao from Bali"                                                                                                          , null),
            new Dish("Tea",                                         [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             0,      "",               ""                                                                                                                                                                     , null),
            new Dish("Hot Ginger Tea",                              [""],                "", ["harmony hill", "the jungle nook"], ["breakfast", "lunch", "dinner", "snack", "extra"], "coffee",   500,             30000,  "",               "With lontar nectar. Black tea optional"                                                                                                                               , null),
        ];
        
        let errorCount = 0;
        const nDishes = dishes.length;
        for(let i = 0; i < nDishes; i++) {
            const dish = dishes[i];
            const res = await dish.upload((e) => {
                console.log(`Upload error for ${dish.id}`, e);
                errorCount++; 
            });
     
            console.log(`Uploaded ${(i+1)}/${nDishes} ${dish.id}`);
        }
        console.log(`Dishes upload complete. Errors: ${errorCount}`);
    }
}
